package com.nox.assistant

data class ChatRequest(val session_id: String, val message: String, val speak: Boolean = false)
data class ChatResponse(val reply: String, val audio_url: String?)
data class TextKnowledgeRequest(val text: String, val name: String = "manual text")
data class UrlKnowledgeRequest(val url: String, val name: String? = null)
data class MemoryRequest(val fact: String)
data class KnowledgeItem(val id: String, val source_type: String, val source_name: String, val added_at: String)
data class MemoryItem(val id: Int, val fact: String, val created_at: String)
data class IdResponse(val doc_id: String?)
data class MemoryIdResponse(val id: Int)
data class DeleteResult(val deleted: String?, val chunks_removed: Int?, val fully_removed: Boolean?)
data class PersonalityText(val text: String)
data class ChatSummary(val id: String, val name: String, val created_at: String, val updated_at: String)
data class CreateChatRequest(val name: String? = null)
data class CreateChatResponse(val id: String)
data class SaveToMemoryResponse(val facts_saved: List<String>, val ids: List<Int>)
data class CodeExecutionState(val enabled: Boolean)
