SERVER_URL = "http://localhost:8420"
SESSION_ID = "windows-main"

WAKE_PHRASE = "hey nox"
SLEEP_PHRASE = "nox sleep"

SAMPLE_RATE = 16000
PASSIVE_CHUNK_SECONDS = 3
COMMAND_CHUNK_SECONDS = 5

WHISPER_MODEL_SIZE = "base"
